[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
md5 = "0.7.0"
regex = "1.11.1"
indoc = "2.0.6"
itertools = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
primes = "0.4.0"
